/*
OSV

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package osvdev

import (
	"encoding/json"
)

// checks if the OsvReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OsvReference{}

// OsvReference Reference URL.
type OsvReference struct {
	Type *OsvReferenceType `json:"type,omitempty"`
	// Required. The URL.
	Url *string `json:"url,omitempty"`
}

// NewOsvReference instantiates a new OsvReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOsvReference() *OsvReference {
	this := OsvReference{}
	var type_ OsvReferenceType = OSVREFERENCETYPE_NONE
	this.Type = &type_
	return &this
}

// NewOsvReferenceWithDefaults instantiates a new OsvReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOsvReferenceWithDefaults() *OsvReference {
	this := OsvReference{}
	var type_ OsvReferenceType = OSVREFERENCETYPE_NONE
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OsvReference) GetType() OsvReferenceType {
	if o == nil || IsNil(o.Type) {
		var ret OsvReferenceType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OsvReference) GetTypeOk() (*OsvReferenceType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OsvReference) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given OsvReferenceType and assigns it to the Type field.
func (o *OsvReference) SetType(v OsvReferenceType) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *OsvReference) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OsvReference) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *OsvReference) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *OsvReference) SetUrl(v string) {
	o.Url = &v
}

func (o OsvReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OsvReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableOsvReference struct {
	value *OsvReference
	isSet bool
}

func (v NullableOsvReference) Get() *OsvReference {
	return v.value
}

func (v *NullableOsvReference) Set(val *OsvReference) {
	v.value = val
	v.isSet = true
}

func (v NullableOsvReference) IsSet() bool {
	return v.isSet
}

func (v *NullableOsvReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOsvReference(val *OsvReference) *NullableOsvReference {
	return &NullableOsvReference{value: val, isSet: true}
}

func (v NullableOsvReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOsvReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


